### ISSUE TITLE
memory error when trying to run mntd.query() with frequency.by.richness

### ISSUE THREAD

**Issue by nick-youngblut** [constantinosTsirogiannis/PhyloMeasures#1]
I'm trying to run:

```
mntd.query(tree, m, standardize = TRUE, null.model = 'frequency.by.richness',
                    abundance.weights = mean_taxon_rel_abunds, reps=1000)
```

The error:

```
Traceback:
 1: mntd.query.weighted(tree, matrix, abundance.weights, standardize,     null.model, reps, my.seed)
 2: mntd.query(gtdb_phy, m, standardize = TRUE, null.model = "frequency.by.richness",     abundance.weights = taxon_abund, reps = 1000, seed = my_seed)
 3: eval(expr, envir, enclos)
 4: eval(expr, envir, enclos)
 5: withVisible(eval(expr, envir, enclos))
 6: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler,     error = eHandler, message = mHandler)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
11: try(f, silent = TRUE)
12: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir,     enclos)), warning = wHandler, error = eHandler, message = mHandler))
13: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr,     envir, enclos)), warning = wHandler, error = eHandler, message = mHandler)))
14: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler, include_timing = include_timing)
15: evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,     stop_on_error = 1L)
16: doTryCatch(return(expr), name, parentenv, handler)
17: tryCatchOne(expr, names, parentenv, handlers[[1L]])
18: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
19: doTryCatch(return(expr), name, parentenv, handler)
20: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
21: tryCatchList(expr, classes, parentenv, handlers)
22: tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,     stop_on_error = 1L), interrupt = function(cond) {    log_debug("Interrupt during execution")    interrupted <<- TRUE}, error = .self$handle_error)
23: executor$execute(msg)
24: handle_shell()
25: kernel$run()
26: IRkernel::main()
```

The same error occurs if I use that taxon abundance vector with pd.query() or other such functions. Using the "sequential" null model also causes the error. Even using an abundance weight vector drawn from `runif(min=1 max=10)` causes the error. The abund-weight vector names match the phylogeny tip labels. The count matrix is 3348 * 3550. There are more tips in the phylogeny than in the count matrix or abund-weight vector.

**Comment by nick-youngblut** [comment]
A weird outcome with my data: mntd.query() with the "uniform" null model generates 0 values for all samples. All standardized PD and MPD values with the "uniform" null model are <1 (all 3348 samples)

**Comment by nick-youngblut** [comment]
`mntd.query(standardize = TRUE, null.model='uniform')` returns all zero values in < 1.5 sec, while PD and MPD require 1-2 minutes, which indicates that `mntd.query` is hitting some internal error and just returning 0 values instead of actually running all 1000 replicates.

**Comment by constantinosTsirogiannis** [comment]
Hi Nick,

Thanks for highlighting that. I am a bit puzzled that all these errors from different functions happen on the same dataset, so I am wondering if it is  an issue with the correct representation of the dataset. Could you provide a minimum example where the issue appears?

**Comment by constantinosTsirogiannis** [comment]
> There are more tips in the phylogeny than in the count matrix or abund-weight vector.

That sounds like the issue. What happens if you adjust the matrix/abundance vector so that their columns match 1-by-1 the tree tips?

**Comment by nick-youngblut** [comment]
> That sounds like the issue

That didn't help. I still get the same errors and weird output.

**Comment by nick-youngblut** [comment]
After some more work, I was able to get an error instead of just a crash for `mntd.query`, and the issue was due to not using an ultrametric tree. It might be good to include `ape::is.ultrametric` at the start of that function.

**Comment by nick-youngblut** [comment]
Is there anyway quickly to convert a large tree (n=~3500 tips) to ultrametric? Using the following does not scale well:
```
phy_obj %>%
    multi2di %>%
    compute.brlen(1) %>%
    chronos
```

**Comment by constantinosTsirogiannis** [comment]
Yes, as mentioned in the documentation this metric can only process ultrametric trees when called in its standardized form. This is because the computational problem of extracting the exact statistical moments of this metric is intractable for general trees. 

As it comes to converting a tree to ultrametric, the question is which method you want to use for generating the branch lengths. Unfortunately, on the R level any simple approach is way too slow.

**Comment by constantinosTsirogiannis** [comment]
Let me know if there is something else regarding this issue. Otherwise, I am going to close this one.
